M48
; DRILL file {KiCad 7.0.10} date Mon Jan 15 21:06:25 2024
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-01-15T21:06:25-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.10
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.350
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.000
%
G90
G05
T1
X115.369Y-115.75
X188.519Y-115.75
T2
X104.7Y-93.16
X160.3Y-93.16
M30
